# Generated by Django 5.2.8 on 2025-12-01 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('transport_km', models.FloatField(default=0, help_text='Weekly transport distance in km')),
                ('electricity_kwh', models.FloatField(default=0, help_text='Monthly electricity consumption in kWh')),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('meat_light', 'Meat 1-2 times/week'), ('meat_medium', 'Meat 3-5 times/week'), ('meat_heavy', 'Meat daily')], default='meat_medium', max_length=20)),
                ('waste_kg', models.FloatField(default=0, help_text='Weekly waste in kg')),
                ('total_co2e', models.FloatField(help_text='Total CO2 equivalent in kg/year')),
                ('transport_co2e', models.FloatField(help_text='Transport CO2e in kg/year')),
                ('electricity_co2e', models.FloatField(help_text='Electricity CO2e in kg/year')),
                ('diet_co2e', models.FloatField(help_text='Diet CO2e in kg/year')),
                ('waste_co2e', models.FloatField(help_text='Waste CO2e in kg/year')),
                ('suggestions', models.JSONField(blank=True, help_text='Personalized reduction suggestions', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Region name (e.g., Nairobi, Mombasa)', max_length=200)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude in decimal degrees', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude in decimal degrees', null=True)),
                ('location_data', models.JSONField(blank=True, help_text='Additional location data', null=True)),
                ('population', models.IntegerField(blank=True, help_text='Population count', null=True)),
                ('area_sq_km', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
                ('climate_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('elevation', models.FloatField(blank=True, help_text='Elevation in meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='climate_reg_name_51d5f0_idx'), models.Index(fields=['country'], name='climate_reg_country_cf895a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('haze', 'Haze/Smog'), ('deforestation', 'Deforestation'), ('pollution', 'Pollution'), ('wildfire', 'Wildfire'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField()),
                ('predicted_temperature', models.FloatField()),
                ('predicted_rainfall', models.FloatField()),
                ('temperature_lower', models.FloatField(blank=True, null=True)),
                ('temperature_upper', models.FloatField(blank=True, null=True)),
                ('rainfall_lower', models.FloatField(blank=True, null=True)),
                ('rainfall_upper', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.region')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'unique_together': {('region', 'prediction_date')},
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Time of measurement')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rainfall', models.FloatField(default=0, help_text='Rainfall in mm (cumulative since last reading)')),
                ('air_quality_index', models.FloatField(blank=True, help_text='Air Quality Index (0-500)', null=True)),
                ('wind_speed', models.FloatField(default=0, help_text='Wind speed in m/s')),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction in degrees', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True)),
                ('uv_index', models.FloatField(blank=True, help_text='UV Index', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Visibility in meters', null=True)),
                ('source', models.CharField(choices=[('api', 'Weather API'), ('sensor', 'Local Sensor'), ('manual', 'Manual Entry'), ('predicted', 'ML Prediction')], default='api', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='climate.region')),
            ],
            options={
                'verbose_name_plural': 'Climate Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['region', 'timestamp'], name='climate_cli_region__4e5a12_idx'), models.Index(fields=['timestamp'], name='climate_cli_timesta_aca75f_idx'), models.Index(fields=['temperature'], name='climate_cli_tempera_3f7168_idx')],
                'unique_together': {('region', 'timestamp')},
            },
        ),
    ]
