# Generated by Django 5.2.8 on 2025-12-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('total_rainfall', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('avg_wind_speed', models.FloatField()),
                ('predicted_temperature', models.FloatField(blank=True, null=True)),
                ('predicted_rainfall', models.FloatField(blank=True, null=True)),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='climate.region')),
            ],
            options={
                'verbose_name_plural': 'Monthly Climate Data',
                'ordering': ['-year', '-month'],
                'unique_together': {('region', 'year', 'month')},
            },
        ),
    ]
