# Generated by Django 5.2.8 on 2025-12-02 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_monthlyclimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclimate',
            name='data_source',
            field=models.CharField(choices=[('aggregated', 'Aggregated from ClimateData'), ('api', 'Monthly API Data'), ('predicted', 'ML Prediction'), ('manual', 'Manual Entry')], default='aggregated', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlyclimate',
            name='rainfall_anomaly',
            field=models.FloatField(blank=True, help_text='Rainfall anomaly from historical average', null=True),
        ),
        migrations.AddField(
            model_name='monthlyclimate',
            name='temperature_anomaly',
            field=models.FloatField(blank=True, help_text='Temperature anomaly from historical average', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='avg_humidity',
            field=models.FloatField(help_text='Average relative humidity percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='avg_temperature',
            field=models.FloatField(help_text='Average temperature in Celsius'),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='avg_wind_speed',
            field=models.FloatField(help_text='Average wind speed in m/s'),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='max_temperature',
            field=models.FloatField(help_text='Maximum temperature in Celsius'),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='min_temperature',
            field=models.FloatField(help_text='Minimum temperature in Celsius'),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='predicted_rainfall',
            field=models.FloatField(blank=True, help_text='Predicted total rainfall for this month', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='predicted_temperature',
            field=models.FloatField(blank=True, help_text='Predicted average temperature for this month', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='prediction_confidence',
            field=models.FloatField(blank=True, help_text='Prediction confidence percentage (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='monthlyclimate',
            name='total_rainfall',
            field=models.FloatField(help_text='Total rainfall in mm'),
        ),
        migrations.AddIndex(
            model_name='monthlyclimate',
            index=models.Index(fields=['region', 'year', 'month'], name='climate_mon_region__7dc06f_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclimate',
            index=models.Index(fields=['year', 'month'], name='climate_mon_year_079eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclimate',
            index=models.Index(fields=['avg_temperature'], name='climate_mon_avg_tem_f774ce_idx'),
        ),
    ]
